name: "Analyzer"

on:
  workflow_call:

jobs:
  analyzer:
    strategy:
      matrix:
        sdk: [stable, 3.2.1, 3.1.5, 3.0.7]
        os: [ubuntu-latest, windows-latest, macos-latest]

    name: "Code Analyzer"
    runs-on: ${{ matrix.os }}

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4.1.1

      - name: "Setup Dart SDK"
        if: success()
        uses: dart-lang/setup-dart@v1.6.0
        with:
          sdk: ${{ matrix.sdk }}

      - name: "Enable Derry"
        if: success()
        run: dart pub global activate derry || false

      - name: "Run Analyzer"
        if: success()
        run: |
          derry update || false
          derry analyze || false
